
import TopNav from '../_components/topNav'


import 'material-icons/iconfont/material-icons.css';




export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({
    children, // will be a page or nested layout
}: {
    children: React.ReactNode
}) {
    return (
        <div className='w-full md:m-0 md:p-0 bg-white justify-start md:min-h-screen flex flex-col md:flex-row'>
            {children}
        </div>

    )
}


